name: Deploy to AdvanceTech PH
on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-southeast-1
  CONTAINER_NAME: advancetechph

defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    environment:
        name: shared
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      image: ${{ steps.build-image.outputs.image }}
      registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
      # - uses: act10ns/slack@v1
      #     env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   with:
      #     status: starting
      #     channel: '#panicroom'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Git Branch
        id: branch
        run: |
          echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
          echo sample1
          echo ${GITHUB_REF#refs/*/}

      - name: Sample
        run: echo ${{ github.head_ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SHARED_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SHARED_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker pull $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:latest
          # docker tag $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:latest
          docker tag $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:latest $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          # docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:latest
          echo "::set-output name=image::${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG"
          echo $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG


  deploy-staging:
    needs: build
    # if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy to staging
    # environment:
    #     name: staging
        # url: ${{ steps.deploy_staging.outputs.webapp-url }}

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.STAGING_TASK_FAMILY }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@97587c9d45a4930bf0e3da8dd2feb2a463cf4a3a
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        id: deploy-to-ecs
        uses: aws-actions/amazon-ecs-deploy-task-definition@de0132cf8cdedb79975c6d42b77eb7ea193cf28e
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.STAGING_ECS_SERVICE }}
          cluster: ${{ secrets.STAGING_ECS_CLUSTER }}
          wait-for-service-stability: true
      # - uses: rnvillacrusis/slack-notifs@1
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #     channel: '#panicroom'
      #   if: always()

  # deploy-prod:
  #   needs: deploy-staging
  #   name: Deploy to production
  #   environment:
  #       name: production
  #       # url: ${{ steps.deploy_staging.outputs.webapp-url }}

  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read
  #   steps:
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.PROD_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.PROD_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Download task definition
  #       run: |
  #         aws ecs describe-task-definition --task-definition ${{ secrets.PROD_TASK_FAMILY }} --query taskDefinition > task-definition.json

  #     - name: Fill in the new image ID in the Amazon ECS task definition
  #       id: task-def
  #       uses: aws-actions/amazon-ecs-render-task-definition@97587c9d45a4930bf0e3da8dd2feb2a463cf4a3a
  #       with:
  #         task-definition: task-definition.json
  #         container-name: ${{ env.CONTAINER_NAME }}
  #         image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

  #     - name: Deploy Amazon ECS task definition
  #       uses: aws-actions/amazon-ecs-deploy-task-definition@de0132cf8cdedb79975c6d42b77eb7ea193cf28e
  #       with:
  #         task-definition: ${{ steps.task-def.outputs.task-definition }}
  #         service: ${{ secrets.PROD_ECS_SERVICE }}
  #         cluster: ${{ secrets.PROD_ECS_CLUSTER }}
  #         wait-for-service-stability: true

      # - uses: rnvillacrusis/slack-notifs@1
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #     channel: '#panicroom'
      #   if: always()
